//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autosalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Availability
    {
        public int Id { get; set; }
        public int Id_Firms { get; set; }
        public int Id_Auto { get; set; }
        public int Availability1 { get; set; }
    
        public virtual Auto Auto { get; set; }
        public virtual Firms Firms { get; set; }
    }
}
